 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: sample-java-ingress
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: sample-java.local
     http:
       paths:
       - path: /
         backend:
           serviceName: sample-java
           servicePort: 8080