apiVersion: v1
kind: Service
metadata:
  name: sample-java
  labels:
    app: sample-java
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sample-java2